{% set name = "django-environ" %}
{% set version = "0.8.0" %}
{% set sha256 = "f77f8890d4cdaf53c3f233bc4367c219d3e8f15073959f8decffc72fd64321c2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - django >=1.8
    - six

about:
  home: https://github.com/joke2k/django-environ
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Django-environ allows you to utilize 12factor inspired environment variables to configure your Django application.
  description: |
    Django-environ allows you to utilize 12factor inspired environment variables to configure your Django application.
    This module is a merge of:
      -envparse
      -honcho
      -dj-database-url
      -dj-search-url
      -dj-config-url
      -django-cache-url

    and inspired by:
      -12factor
      -12factor-django
      -Two Scoops of Django

  doc_url: https://django-environ.readthedocs.io/en/latest/
  dev_url: https://github.com/joke2k/django-environ

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
